//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AECSmartPole.rc
//
#define IDOK2                           3
#define IDC_CLEARALL                    3
#define IDS_PROJNAME                    100
#define IDC_FLOATEDIT                   101
#define IDC_TABLE_TEXTHT                101
#define IDC_MAST_RATE                   101
#define IDD_AEC_ADD_POLE                200
#define IDD_SP_POLE_INFO                200
#define IDC_ADDPOLE_NEW                 201
#define IDC_ADDPOLE_EXISTING            202
#define IDC_ADDPOLE_REMOVE              203
#define IDD_SP_STREETLIGHT_INFO         203
#define IDD_SP_LIGHT_INFO               203
#define IDC_ADDPOLE_REPLACE             204
#define IDC_ADDPOLE_RELOCATE            205
#define IDD_SP_OPTIONS                  205
#define IDC_ADDPOLE_GHOST               206
#define IDD_TABLE_COLUMNS               206
#define IDD_SP_CABLE                    207
#define IDC_ADDPOLE_NUMBER              208
#define IDC_POLE_NUMBER                 208
#define IDD_SP_LIGHT_REPLACE            208
#define IDC_ADDPOLE_FIELD_NUMBER        209
#define IDC_POLE_FIELD_NUMBER           209
#define IDC_POLE_FIELD_NUMBER_NEW       209
#define IDC_ADDPOLE_TYPE                210
#define IDC_ADDPOLE_SIZE                210
#define IDC_POLE_SIZE                   210
#define EDITLIGHT                       210
#define ID_EDITLIGHT                    210
#define IDC_ADDPOLE_FOOTING             211
#define IDC_POLE_FOOTING                211
#define IDC_ADDPOLE_POLE_DIA            212
#define IDC_POLE_DIA                    212
#define IDC_POLE_FIELD_NUMBER2          213
#define IDC_POLE_FIELD_NUMBER_EXIST     213
#define IDC_ADDPOLE_STAY_TYPE           214
#define IDC_POLE_STAY_TYPE              214
#define IDC_ADDPOLE_HOLE_DIA            215
#define IDC_POLE_HOLE_DIA               215
#define IDC_ADDPOLE_HOLE_DEPTH          216
#define IDC_POLE_HOLE_DEPTH             216
#define IDC_POLE_DESCRIPTION            217
#define IDC_ADDPOLE_LANTERN_BRACKET     218
#define IDC_POLE_LANTERN_BRACKET        218
#define IDC_CHECK2                      219
#define IDC_POLE_DISPLAY                219
#define IDC_LIGHT_NON_STANDARD          219
#define IDC_STATIC_POLE_INFO            220
#define IDC_STATIC_POLE_LANTERNS        221
#define IDC_ADDPOLE_LANTERN_STATUS      222
#define IDC_POLE_LANTERN_STATUS         222
#define IDC_ADDPOLE_CLEAR_ALL           223
#define IDC_POLE_CLEAR_ALL              223
#define IDC_STATIC_POLE_CONS            224
#define IDC_ADDPOLE_POLE_DIA2           225
#define IDC_POLE_SPAN_LENGTH            225
#define IDC_ADDPOLE_HOLE_DIA2           226
#define IDC_POLE_LINE_DEV_DEG           226
#define IDC_STATIC_POLE_HV              227
#define IDC_ADDPOLE_HV_LIST             228
#define IDC_POLE_HV_LIST                228
#define IDC_ADDPOLE_HV_ABC              229
#define IDC_POLE_HV_ABC                 229
#define IDC_ADDPOLE_HV_BARE             230
#define IDC_POLE_HV_BARE                230
#define IDC_ADDPOLE_HV_CCT              231
#define IDC_POLE_HV_CCT                 231
#define IDC_POLE_HV_OTHER               231
#define IDC_ADDPOLE_LV_LIST             232
#define IDC_POLE_LV_LIST                232
#define IDC_ADDPOLE_LV_ABC              233
#define IDC_POLE_LV_ABC                 233
#define IDC_ADDPOLE_LV_BARE             234
#define IDC_POLE_LV_BARE                234
#define IDC_ADDPOLE_LV_CCT              235
#define IDC_POLE_LV_CCT                 235
#define IDC_POLE_LV_OTHER               235
#define IDC_STATIC_POLE_LV              236
#define IDC_ADDPOLE_STATUS              238
#define IDC_POLE_STAY_REQ               239
#define IDC_STATIC_LANTERN_INFO         240
#define IDC_POLE_STATUS                 241
#define IDC_LIGHT_LANTERN_STATUS        242
#define IDC_CHECK1                      243
#define IDC_LIGHT_COLUMN_REQ            243
#define IDC_CUR_DWG_ONLY                243
#define IDC_SELECT_ALL                  243
#define IDC_CABLE_START                 243
#define IDC_LIGHT_COLUMN_STATUS         244
#define IDC_REMOVE_ALL                  244
#define IDC_LIGHT_COLUMN_STATUS2        245
#define IDC_LIGHT_LANTERN_SCHEDULE      245
#define IDC_LIGHT_SCHEDULE              245
#define IDC_LIGHT_TYPE                  246
#define IDC_LIGHT_TYPE2                 247
#define IDC_LIGHT_LAMP                  247
#define IDC_LIGHT_LANTERN_STOCK         248
#define IDC_LIGHT_LAMP_STOCK            249
#define IDC_LIGHT_MAST                  250
#define IDC_LIGHT_MAST_STOCK            251
#define IDC_LIGHT_RATE_CODE             252
#define IDC_LIGHT_KINGBOLT              253
#define IDC_LIGHT_OUTREACH              254
#define IDC_LIGHT_OUTREACH_STOCK        255
#define IDC_LIGHT_BRACKET               256
#define IDC_LIGHT_LAMP_STOCK4           257
#define IDC_LIGHT_BRACKET_STOCK         257
#define IDC_STATIC_CHARGE               258
#define IDC_STATIC_ASSET                259
#define IDC_LIGHT_ASSET_COLUMN          260
#define IDC_LIGHT_ASSET_LANTERN         261
#define IDC_LIGHT_ASSET_CATEGORY        262
#define IDC_LIGHT_CHARGE_LIST           263
#define IDC_STATIC_POLE                 264
#define IDC_LIGHT_LANTERN_LOCATION      264
#define IDC_POLE_TEXT_STYLE             265
#define IDC_Outreach_Rate               265
#define IDC_POLE_TEXT_HEIGHT            266
#define IDC_Bracket_Rate                266
#define IDC_POLE_DIAMETER               267
#define IDC_TABLE_LIST                  267
#define IDC_SCH_TEXT_STYLE              268
#define IDC_SCH_TEXT_HEIGHT             269
#define IDC_TABLE_STYLE                 269
#define IDC_STATIC_SCHEDULE             270
#define IDC_POLE_DIAMETER2              271
#define IDC_TABLE_LAYOUT                271
#define IDC_CONDUCTOR_TYPE              276
#define IDC_POLE_HV_SEL                 277
#define IDC_CONDUCTOR_TYPE2             277
#define IDC_CONDUCTOR_LTYPE             277
#define IDC_POLE_LV_SEL                 278
#define IDC_LIGHT_REPLACE               278
#define IDC_LIGHT_REPLACE_NON_STANDARD  279
#define IDC_LIGHT_REPLACE_SCHEDULE      280
#define IDC_LIGHT_REPLACE_LAMP          281
#define IDC_LIGHT_REPLACE_TYPE          282
#define IDC_LIGHT_REPLACE_RATE_CODE     283
#define IDC_LIGHT_REPLACE_CHARGE_LIST   284
#define IDC_LIGHT_REPLACE_ASSET_CATEGORY 285
#define IDC_LIGHT_REPLACE_ASSET_COLUMN  286
#define IDC_LIGHT_REPLACE_ASSET_LANTERN 287
#define IDC_STATIC_REPLACE_ASSET        288
#define IDC_STATIC_REPLACE_CHARGE       289
#define IDC_EDIT1                       290
#define IDC_LIGHTNUMBER                 290
#define IDC_LIGHT_NUMBER                290
#define IDC_Column_Stock_Code           291
#define IDC_Rag_Bolt                    292
#define IDC_Foundation_Type             293
#define IDC_Mounting_Height             294
#define IDC_EDIT4                       297
#define IDC_EDIT2                       298

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        224
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         299
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
