#pragma once
enum COMPONENT_TYPE
{
	COMP_INVALID = -1,
	COMP_POINT = 1,
	COMP_TEXTPOINT = 2,
	COMP_COMPOSITE_POLYLINE = 3,
	COMP_BOUNDARY = 4,
	COMP_POLYGON = 5,
	COMP_COMPOSITE_POLYGON = 6,
    COMP_COMPOSITE_MLINE = 7
};